GET http://localhost:5000/employee


###
POST http://localhost:5000/employee
content-Type: application/json

{
    "name": "Anant Loduram",
    "skills": ["html", "css", "js", "MERN"],
    "gender": "male"
}

###
DELETE http://localhost:5000/employee/5f063bf8913c79213873c4f6
###
DELETE http://localhost:5000/employee/5f063bc7913c79213873c4f5
###
DELETE http://localhost:5000/employee/5f063bc7913c79213873c4f5
###
DELETE http://localhost:5000/employee/5f063bc7913c79213873c4f5


###
PATCH http://localhost:5000/employee/5f05ab4e3cf6ed2b60e9fbbf
Content-Type: application/json

{
    "skills": ["ruby", "laravel"]
}
